name: neon_http_client
description: A http client for the Neon framework.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  built_collection: ^5.0.0
  cookie_store:
    path: ../../../cookie_store
  http: ^1.0.0
  http_parser: ^4.0.0
  interceptor_http_client:
    path: ../../../interceptor_http_client
  logging: ^1.0.0
  meta: ^1.0.0
  nextcloud: ^8.1.0

dev_dependencies:
  http_client_conformance_tests:
    git:
      url: https://github.com/dart-lang/http
      path: pkgs/http_client_conformance_tests
      ref: 531d3e587c3214ad07bed1f52fac3f01112bc1ed
  mocktail: ^1.0.4
  neon_lints:
    path: ../../../neon_lints
  test: ^1.26.3
