name: neon_http_client
description: A http client for the Neon framework.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  built_collection: ^5.0.0
  cookie_store:
    git:
      url: https://github.com/foldland/cookie_store
      path: packages/cookie_store
      ref: 4280ce0b73d1950a603f6ed78596666db1b59af6
  http: ^1.6.0
  interceptor_http_client:
    git:
      url: https://github.com/foldland/cookie_store
      path: packages/interceptor_http_client
      ref: 4280ce0b73d1950a603f6ed78596666db1b59af6
  logging: ^1.0.0
  meta: ^1.0.0
  nextcloud: ^9.0.0

dev_dependencies:
  http_client_conformance_tests:
    git:
      url: https://github.com/dart-lang/http
      path: pkgs/http_client_conformance_tests
      ref: 907782f5a792e7a5b0ed92f118c0ad91f3ecde51
  mocktail: ^1.0.4
  neon_lints:
    path: ../../../neon_lints
  test: ^1.25.15
