name: neon_workspace
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

workspace:
  - packages/cookie_store
  - packages/cookie_store/packages/cookie_store_conformance_tests
  - packages/dynamite
  - packages/dynamite/example
  - packages/dynamite/packages/dynamite_end_to_end_test
  - packages/dynamite/packages/dynamite_runtime
  - packages/interceptor_http_client
  - packages/neon_framework
  - packages/neon_framework/example
  - packages/neon_framework/packages/account_repository
  - packages/neon_framework/packages/dashboard_app
  - packages/neon_framework/packages/files_app
  - packages/neon_framework/packages/neon_http_client
  - packages/neon_framework/packages/neon_rich_text
  - packages/neon_framework/packages/neon_storage
  - packages/neon_framework/packages/news_app
  - packages/neon_framework/packages/notes_app
  - packages/neon_framework/packages/notifications_app
  - packages/neon_framework/packages/notifications_push_repository
  - packages/neon_framework/packages/sort_box
  - packages/neon_framework/packages/talk_app
  - packages/neon_lints
  - packages/neon_lints/example
  - packages/nextcloud
  - packages/nextcloud/packages/nextcloud_test
  - packages/nextcloud/packages/nextcloud_test_presets

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: 7.0.0

melos:
  name: neon
  repository: https://github.com/nextcloud/neon

  sdkPath: .fvm/flutter_sdk

  ide:
    intellij:
      enabled: false

  command:
    version:
      hooks:
        # Needed until https://github.com/invertase/melos/issues/591 is supported
        post: |
          git commit --amend --signoff --no-edit

  scripts:
    format: dart format --line-length 120 .
    format:check: dart format --output=none --set-exit-if-changed --line-length 120 .
    analyze: >
      dart analyze --fatal-infos . &&
      rm -rf packages/neon_framework/example/linux/flutter/ephemeral/ &&
      dart run custom_lint --fatal-infos .
    test: >
      melos run test:dart &&
      melos run test:flutter
    test:dart: >
      melos exec --no-flutter --concurrency=1 --fail-fast --dir-exists=test -- "
        dart test --concurrency=$(nproc --all) --coverage=coverage &&
        dart pub global run coverage:format_coverage --packages=MELOS_ROOT_PATH/.dart_tool/package_config.json --report-on=lib --lcov -o ./coverage/lcov.info -i ./coverage
      "
    test:flutter: melos exec --flutter --concurrency=1 --fail-fast --dir-exists=test -- flutter test --concurrency=$(nproc --all) --coverage
    generate:neon:build_runner: melos exec --scope="neon*" --file-exists="build.yaml" -- dart run build_runner build --delete-conflicting-outputs && melos run format
    generate:neon:l10n: melos exec --flutter --dir-exists="lib/l10n" flutter gen-l10n && melos run format
