name: sort_box
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  built_collection: ^5.0.0
  meta: ^1.0.0

dev_dependencies:
  neon_lints:
    path: ../../../neon_lints
  test: ^1.26.3
