name: neon_storage
description: Storage management and abstractions for the neon framework.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  built_collection: ^5.0.0
  cookie_store:
    git:
      url: https://github.com/foldland/cookie_store
      path: packages/cookie_store
      ref: 4280ce0b73d1950a603f6ed78596666db1b59af6
  http: ^1.0.0
  logging: ^1.0.0
  meta: ^1.0.0
  nextcloud: ^9.0.0
  path: ^1.9.0
  sqflite_common: ^2.0.0
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^1.0.0

dev_dependencies:
  cookie_store_conformance_tests:
    git:
      url: https://github.com/foldland/cookie_store
      path: packages/cookie_store_conformance_tests
      ref: 4280ce0b73d1950a603f6ed78596666db1b59af6
  mocktail: ^1.0.4
  neon_lints:
    path: ../../../neon_lints
  test: ^1.25.15
