name: neon_framework
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.27.0

dependencies:
  account_repository:
    path: packages/account_repository
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  built_collection: ^5.0.0
  built_value: ^8.9.0
  collection: ^1.0.0
  cookie_store:
    path: ../cookie_store
  crypto: ^3.0.0
  cupertino_icons: ^1.0.0 # Do not remove this, is it needed on iOS/macOS. It will not include icons on other platforms because Apple forbids it.
  dynamic_color:
    git:
      url: https://github.com/provokateurin/flutter-packages
      path: packages/dynamic_color
      # dynamic_color/flutter_test
      ref: faeecdf6c6b748af308c8eece8b3681c8cb6fbd8
  dynamite_runtime: ^0.5.0+1
  equatable: ^2.0.0
  file_picker: ^10.0.0
  filesize: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_blurhash: ^0.9.0
  flutter_local_notifications: ^19.0.0
  flutter_localizations:
    sdk: flutter
  flutter_material_design_icons: ^1.1.7296
  flutter_native_splash: ^2.0.0
  flutter_svg: ^2.0.0
  flutter_zxing: ^2.0.0
  go_router: ^16.0.0
  http: ^1.0.0
  image: ^4.0.0
  intl: ^0.20.2
  logging: ^1.0.0
  meta: ^1.0.0
  neon_http_client:
    path: packages/neon_http_client
  nextcloud: ^8.1.0
  notifications_push_repository:
    path: packages/notifications_push_repository
  package_info_plus: ^8.0.0
  path: ^1.0.0
  path_provider: ^2.1.0
  permission_handler: ^12.0.0
  provider: ^6.0.0
  quick_actions: ^1.0.0
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.0
  shared_preferences_platform_interface: ^2.3.2
  sort_box:
    path: packages/sort_box
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^1.0.0
  timezone: ^0.10.1
  universal_io: ^2.0.0
  url_launcher: ^6.1.4
  vector_graphics: ^1.0.0
  web: ^1.0.0
  window_manager: ^0.5.0
  xml: ^6.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.9.0
  built_value_generator: ^8.10.1
  code_builder: ^4.10.1
  cookie_store_conformance_tests:
    path: ../cookie_store/packages/cookie_store_conformance_tests
  crypton: ^2.2.1
  custom_lint: ^0.7.6
  dart_style: ^3.1.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^3.0.0
  mocktail: ^1.0.4
  neon_lints:
    path: ../neon_lints
  package_info_plus_platform_interface: ^3.2.1
  permission_handler_platform_interface: ^4.3.0
  plugin_platform_interface: ^2.1.8
  string_normalizer: ^0.3.5
  url_launcher_platform_interface: ^2.3.2
  vector_graphics_compiler: ^1.1.19
  version: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/server/
  plugin:
    platforms:
      linux:
        dartPluginClass: LinuxNeonPlatform
      android:
        dartPluginClass: AndroidNeonPlatform
      web:
        pluginClass: WebNeonPlatform
        fileName: src/platform/web.dart
