@startuml architecture

package "Neon framework" {
    component neon
    component nextcloud
    component settings
    component sort_box
    component file_icons
}

package "Clients" {
    component neon_files
    component neon_news
    component neon_notes
    component neon_notifications
}

package "OpenAPI" {
    component dynamite
    component specifications
}

component app

app ..> neon_files
app ..> neon_news
app ..> neon_notes
app ..> neon_notifications

neon_files --> neon
neon_news --> neon
neon_notes --> neon
neon_notifications --> neon


neon --> nextcloud
neon --> sort_box
neon --> file_icons

dynamite --> nextcloud
specifications --> nextcloud

@enduml