@startuml architecture

package "Neon framework" {
    component neon_framework
    component nextcloud
    component sort_box
    component files_icons
}

package "Clients" {
    component dashboard_app
    component files_app
    component news_app
    component notes_app
    component notifications_app
}

package "OpenAPI" {
    component dynamite
    component specifications
}

component app

app ..> dashboard_app
app ..> files_app
app ..> news_app
app ..> notes_app
app ..> notifications_app

dashboard_app --> neon_framework
files_app --> neon_framework
news_app --> neon_framework
notes_app --> neon_framework
notifications_app --> neon_framework


neon_framework --> nextcloud
neon_framework --> sort_box
neon_framework --> files_icons

dynamite --> nextcloud
specifications --> nextcloud

@enduml
