name: Generate
on:
  pull_request:

concurrency:
  group: generate-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check changes
    runs-on: ubuntu-24.04
    outputs:
      src: ${{ steps.changes.outputs.src}}
    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - .github/workflows/**
              - external/**
              - tool/**
              - packages/dynamite/**
              - .fvmrc

  dart:
    name: Dart
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.src != 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Submodules
        run: git submodule update --init --depth 0

      - name: Install dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1
        with:
          sdk: 3.7
      - name: Setup
        run: ./tool/setup.sh

      - name: Generate dynamite end to end test
        run: |
          ./tool/generate-dynamite-e2e-test.sh
          git --no-pager diff --exit-code

      - name: Generate dynamite petstore example
        run: |
          ./tool/generate-dynamite-petstore-example.sh
          git --no-pager diff --exit-code
